// ExamsForge by SmartSchool Digital
// CBC Senior School Curriculum — Grade 10, 11, 12

export const CBC_CURRICULUM = {
  'Grade 10': {
    subjects: [
      'Mathematics',
      'English',
      'Kiswahili',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      'Agriculture',
      'Computer Science',
      'Home Science',
      'Art and Design',
      'Music',
      'Physical Education',
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Numbers and Algebra',
        'Measurement and Geometry',
        'Statistics and Probability',
        'Financial Mathematics',
      ],
      'English': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Language Use',
        'Literature',
      ],
      'Kiswahili': [
        'Kusikiliza na Kuzungumza',
        'Kusoma',
        'Kuandika',
        'Sarufi na Matumizi ya Lugha',
        'Fasihi',
      ],
      'Biology': [
        'Cell Biology',
        'Biochemistry',
        'Classification of Living Things',
        'Nutrition',
        'Gaseous Exchange',
        'Transport and Excretion',
        'Ecology',
      ],
      'Chemistry': [
        'Atomic Structure and Periodic Table',
        'Chemical Bonding',
        'Acids, Bases and Salts',
        'Stoichiometry',
        'Electrochemistry',
        'Organic Chemistry',
        'Environmental Chemistry',
      ],
      'Physics': [
        'Mechanics',
        'Waves',
        'Electricity and Magnetism',
        'Thermal Physics',
        'Optics',
      ],
      'History and Citizenship': [
        'Pre-Colonial African History',
        'Colonial History of Kenya',
        'Governance and Citizenship',
        'Economic History',
      ],
      'Geography': [
        'Physical Geography',
        'Human Geography',
        'Environmental Geography',
        'Regional Geography',
        'Map Work and Fieldwork',
      ],
      'CRE': [
        'The Bible as a Source of Knowledge',
        'Christian Morality and Ethics',
        'Jesus Christ and His Mission',
        'The Church',
        'Family and Society',
      ],
      'Business Studies': [
        'Business Concepts and Environment',
        'Entrepreneurship',
        'Financial Literacy',
        'Marketing',
        'Office Management',
      ],
      'Agriculture': [
        'Crop Production',
        'Animal Production',
        'Soil and Water Management',
        'Farm Structures and Mechanisation',
        'Agricultural Economics',
      ],
      'Computer Science': [
        'Computer Systems',
        'Programming Fundamentals',
        'Data and Information',
        'Networks and the Internet',
        'Digital Citizenship',
      ],
      'Home Science': [
        'Food and Nutrition',
        'Clothing and Textiles',
        'Housing and Home Management',
        'Family Health',
      ],
      'Life Skills Education': [
        'Self-Awareness and Identity',
        'Interpersonal Relationships',
        'Decision Making and Problem Solving',
        'Citizenship and Social Responsibility',
      ],
    },
  },

  'Grade 11': {
    subjects: [
      'Mathematics',
      'English',
      'Kiswahili',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      'Agriculture',
      'Computer Science',
      'Home Science',
      'Art and Design',
      'Music',
      'Physical Education',
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Numbers and Algebra',
        'Sequences and Series',
        'Measurement and Geometry',
        'Statistics and Probability',
        'Financial Mathematics',
        'Calculus (Introductory)',
      ],
      'English': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Language Use',
        'Literature',
      ],
      'Kiswahili': [
        'Kusikiliza na Kuzungumza',
        'Kusoma',
        'Kuandika',
        'Sarufi na Matumizi ya Lugha',
        'Fasihi',
      ],
      'Biology': [
        'Cell Biology and Biochemistry',
        'Genetics and Heredity',
        'Reproduction',
        'Growth and Development',
        'Regulation and Coordination',
        'Evolution',
        'Applied Biology',
      ],
      'Chemistry': [
        'Reaction Kinetics',
        'Chemical Equilibrium',
        'Thermochemistry',
        'Organic Chemistry',
        'Industrial Chemistry',
        'Analytical Chemistry',
      ],
      'Physics': [
        'Linear and Circular Motion',
        'Work, Energy and Power',
        'Electromagnetism',
        'Electronics',
        'Radioactivity',
        'Waves and Optics',
      ],
      'History and Citizenship': [
        'Nationalism and Independence',
        'Post-Independence Kenya',
        'International Relations',
        'Constitutional Development',
        'Contemporary Issues',
      ],
      'Geography': [
        'Geomorphology',
        'Climatology',
        'Population Geography',
        'Urban Geography',
        'Agriculture and Land Use',
        'Industry and Trade',
      ],
      'CRE': [
        'Christian Living and Modern Challenges',
        'Human Sexuality and Relationships',
        'Social Justice and Stewardship',
        'Faith in Action',
      ],
      'Business Studies': [
        'Business Operations',
        'Financial Accounting',
        'Banking and Insurance',
        'International Trade',
        'Business Ethics and Technology',
      ],
      'Agriculture': [
        'Advanced Crop Production',
        'Livestock Husbandry',
        'Horticulture',
        'Agricultural Finance and Marketing',
        'Agricultural Technology',
      ],
      'Computer Science': [
        'Object-Oriented Programming',
        'Database Management',
        'Web Technologies',
        'Algorithms and Data Structures',
        'Cybersecurity',
      ],
      'Home Science': [
        'Advanced Food Science',
        'Textile Technology',
        'Household Management',
        'Entrepreneurship in Home Science',
      ],
      'Life Skills Education': [
        'Conflict Resolution',
        'Financial Literacy and Planning',
        'Career Guidance',
        'Mental Health and Wellbeing',
      ],
    },
  },

  'Grade 12': {
    subjects: [
      'Mathematics',
      'English',
      'Kiswahili',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      'Agriculture',
      'Computer Science',
      'Home Science',
      'Art and Design',
      'Music',
      'Physical Education',
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Advanced Algebra',
        'Calculus',
        'Vectors and Matrices',
        'Statistics and Probability',
        'Financial Mathematics',
        'Complex Numbers',
      ],
      'English': [
        'Advanced Listening and Speaking',
        'Critical Reading',
        'Advanced Writing',
        'Language and Style',
        'Literature and Criticism',
      ],
      'Kiswahili': [
        'Mawasiliano ya Hali ya Juu',
        'Usomaji wa Kina',
        'Uandishi wa Hali ya Juu',
        'Sarufi ya Kina',
        'Fasihi ya Kina',
      ],
      'Biology': [
        'Molecular Biology and Biotechnology',
        'Ecology and Conservation',
        'Applied Genetics',
        'Human Physiology',
        'Evolution and Biodiversity',
        'Environmental Biology',
      ],
      'Chemistry': [
        'Advanced Organic Chemistry',
        'Environmental and Green Chemistry',
        'Advanced Electrochemistry',
        'Chemical Analysis',
        'Industrial Processes',
        'Nanochemistry (Introduction)',
      ],
      'Physics': [
        'Advanced Mechanics',
        'Electromagnetism and Electronics',
        'Nuclear Physics',
        'Astrophysics (Introduction)',
        'Quantum Physics (Introduction)',
        'Applied Physics',
      ],
      'History and Citizenship': [
        'Kenya and the Global Community',
        'Democracy and Governance',
        'Economic Development and Planning',
        'Human Rights and Justice',
        'Contemporary African Issues',
      ],
      'Geography': [
        'Environmental Management',
        'Global Issues and Sustainable Development',
        'Advanced Map Work and GIS',
        'Transport and Trade',
        'Regional Studies',
      ],
      'CRE': [
        'Christian Responses to Contemporary Issues',
        'Peace and Justice',
        'Christian Vocation and Service',
        'Interfaith Dialogue',
      ],
      'Business Studies': [
        'Advanced Financial Management',
        'Strategic Management',
        'Global Business',
        'Business Innovation and Entrepreneurship',
      ],
      'Agriculture': [
        'Farm Enterprise Management',
        'Sustainable Agriculture',
        'Value Addition and Agribusiness',
        'Research and Innovation in Agriculture',
      ],
      'Computer Science': [
        'Advanced Programming',
        'Artificial Intelligence (Introductory)',
        'Cloud Computing',
        'Software Engineering',
        'Data Science Fundamentals',
      ],
      'Home Science': [
        'Advanced Nutrition and Dietetics',
        'Fashion Design and Technology',
        'Home-Based Enterprise',
        'Community Development',
      ],
      'Life Skills Education': [
        'Entrepreneurship and Innovation',
        'Civic Education and Governance',
        'Global Citizenship',
        'Transition to Adulthood',
      ],
    },
  },
}

// Sub-strands mapped to strands
export const SUBSTRANDS = {
  // Mathematics
  'Numbers and Algebra': ['Indices and Logarithms', 'Quadratic Equations', 'Inequalities', 'Simultaneous Equations', 'Polynomials'],
  'Sequences and Series': ['Arithmetic Progressions', 'Geometric Progressions', 'Binomial Theorem', 'Sum to Infinity'],
  'Measurement and Geometry': ['Trigonometry', 'Circles and Chords', 'Vectors in 2D and 3D', 'Transformation Geometry', 'Constructions'],
  'Statistics and Probability': ['Measures of Central Tendency', 'Measures of Dispersion', 'Probability Theory', 'Distributions', 'Data Representation'],
  'Financial Mathematics': ['Commercial Arithmetic', 'Simple and Compound Interest', 'Annuities and Investments', 'Depreciation'],
  'Calculus (Introductory)': ['Limits and Continuity', 'Differentiation', 'Integration', 'Applications of Calculus'],
  'Calculus': ['Advanced Differentiation', 'Advanced Integration', 'Differential Equations', 'Applications'],
  'Advanced Algebra': ['Complex Numbers', 'Matrices and Determinants', 'Partial Fractions', 'Mathematical Induction'],
  'Vectors and Matrices': ['Matrix Operations', 'Determinants and Inverses', 'Transformations', 'Linear Equations'],

  // Biology
  'Cell Biology': ['Cell Structure and Function', 'Cell Division (Mitosis and Meiosis)', 'Cell Transport', 'Biochemical Reactions'],
  'Cell Biology and Biochemistry': ['Biomolecules', 'Enzyme Action', 'ATP and Energy', 'Metabolic Pathways'],
  'Genetics and Heredity': ['Mendelian Genetics', 'Dihybrid Cross', 'Linkage and Sex-Linked Traits', 'Genetic Disorders'],
  'Reproduction': ['Sexual Reproduction in Humans', 'Reproduction in Plants', 'Fertilisation and Development', 'Reproductive Health'],
  'Regulation and Coordination': ['Nervous System', 'Endocrine System', 'Homeostasis', 'Receptors and Effectors'],
  'Ecology': ['Ecosystems and Biomes', 'Food Webs and Energy Flow', 'Population Ecology', 'Conservation Biology'],
  'Molecular Biology and Biotechnology': ['DNA Structure and Replication', 'Protein Synthesis', 'Genetic Engineering', 'Biotechnology Applications'],

  // Chemistry
  'Atomic Structure and Periodic Table': ['Atomic Models', 'Electronic Configuration', 'Periodic Trends', 'Chemical Families'],
  'Acids, Bases and Salts': ['pH and Indicators', 'Titration and Neutralisation', 'Salt Formation', 'Buffer Solutions'],
  'Stoichiometry': ['Mole Concept', 'Empirical Formulae', 'Limiting Reagent', 'Yield Calculations'],
  'Organic Chemistry': ['Hydrocarbons', 'Functional Groups', 'Reactions of Organic Compounds', 'Polymers'],
  'Reaction Kinetics': ['Rate of Reaction', 'Factors Affecting Rate', 'Activation Energy', 'Catalysis'],
  'Chemical Equilibrium': ['Le Chatelier\'s Principle', 'Equilibrium Constant', 'Industrial Applications', 'Ionic Equilibria'],
  'Thermochemistry': ['Enthalpy Changes', 'Hess\'s Law', 'Bond Energies', 'Calorimetry'],

  // Physics
  'Mechanics': ['Newton\'s Laws of Motion', 'Momentum and Impulse', 'Work, Energy and Power', 'Projectile Motion'],
  'Linear and Circular Motion': ['Equations of Motion', 'Circular Motion', 'Angular Velocity', 'Centripetal Force'],
  'Electromagnetism': ['Magnetic Fields', 'Electromagnetic Induction', 'AC and DC Circuits', 'Transformers'],
  'Waves': ['Wave Properties', 'Sound Waves', 'Electromagnetic Spectrum', 'Interference and Diffraction'],
  'Radioactivity': ['Nuclear Structure', 'Types of Radiation', 'Half-Life', 'Nuclear Reactions and Safety'],
  'Electronics': ['Semiconductors', 'Diodes and Transistors', 'Logic Gates', 'Amplifiers'],

  // History
  'Pre-Colonial African History': ['African Political Systems', 'Trade and Economy', 'Social Organisation', 'African Religions'],
  'Colonial History of Kenya': ['European Exploration', 'Establishment of Colonial Rule', 'African Resistance', 'Colonial Economic Policies'],
  'Nationalism and Independence': ['African Nationalism', 'Kenya African Union', 'Mau Mau', 'Independence Negotiations'],
  'Post-Independence Kenya': ['Constitutional Developments', 'Political Parties', 'Economic Policies', 'Social Development'],
  'Governance and Citizenship': ['Structures of Government', 'Rights and Responsibilities', 'Rule of Law', 'Democratic Governance'],

  // Geography
  'Physical Geography': ['Plate Tectonics', 'Rocks and Minerals', 'Rivers and Valleys', 'Coastal Landforms'],
  'Climatology': ['Weather Systems', 'Climate Zones', 'Climate Change', 'Meteorological Instruments'],
  'Population Geography': ['Population Growth', 'Migration', 'Urbanisation', 'Population Policies'],
  'Map Work and Fieldwork': ['Topographic Maps', 'Geographical Coordinates', 'Data Collection', 'GIS Introduction'],

  // Business Studies
  'Business Concepts and Environment': ['Nature of Business', 'Business Environment', 'Forms of Business Ownership', 'Business Objectives'],
  'Entrepreneurship': ['Entrepreneurial Traits', 'Business Opportunities', 'Business Plan', 'Start-Up Challenges'],
  'Financial Accounting': ['Double Entry Bookkeeping', 'Final Accounts', 'Bank Reconciliation', 'Interpretation of Accounts'],
  'Financial Literacy': ['Personal Finance', 'Budgeting', 'Investment Options', 'Taxation'],

  // Agriculture
  'Crop Production': ['Crop Ecology', 'Land Preparation', 'Planting and Spacing', 'Crop Management and Harvesting'],
  'Animal Production': ['Livestock Selection', 'Animal Nutrition', 'Animal Health', 'Livestock Records'],
  'Soil and Water Management': ['Soil Formation and Types', 'Soil Fertility', 'Irrigation Methods', 'Drainage and Conservation'],
  'Agricultural Economics': ['Farm Planning', 'Costs and Returns', 'Agricultural Marketing', 'Credit and Finance'],
}

export const EXAM_TYPES = ['CAT', 'Midterm', 'End Term', 'Pre-Mock', 'Mock']
export const TERMS = ['Term 1', 'Term 2', 'Term 3']
export const MARKS_OPTIONS = [30, 40, 50, 70, 80, 100]
export const QUESTIONS_OPTIONS = [10, 12, 15, 20, 25]
export const GRADES = Object.keys(CBC_CURRICULUM) // ['Grade 10', 'Grade 11', 'Grade 12']
