// ExamsForge by SmartSchool Digital
// CBC Senior School Curriculum — Grade 10, 11, 12
// All 46 KICD Approved Subjects

export const CBC_CURRICULUM = {
  'Grade 10': {
    subjects: [
      // Core Subjects
      'Mathematics',
      'Essential Mathematics',
      'English',
      'Kiswahili',
      'Community Service Learning',
      // Languages
      'Literature in English',
      'Fasihi ya Kiswahili',
      'Arabic',
      'French',
      'German',
      'Chinese',
      'Indigenous Languages',
      'Sign Language',
      'Kenyan Sign Language',
      // Humanities
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      // Sciences
      'Biology',
      'Chemistry',
      'Physics',
      'General Science',
      // Technical & Applied
      'Agriculture',
      'Computer Studies',
      'Home Science',
      'Aviation',
      'Building and Construction',
      'Electricity',
      'Drawing and Design',
      'Marine and Fisheries',
      'Metalwork',
      'Power Mechanics',
      'Woodwork',
      'Media Technology',
      // Arts & Sports
      'Art and Design',
      'Music and Dance',
      'Theatre and Film',
      'Fine Arts',
      'Sports and Recreation',
      'Physical Education',
      // Life Skills
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Numbers and Algebra',
        'Measurement and Geometry',
        'Statistics and Probability',
        'Financial Mathematics',
      ],
      'Essential Mathematics': [
        'Number and Operations',
        'Measurement and Geometry',
        'Data Handling',
        'Financial Mathematics',
      ],
      'English': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Language Use',
        'Literature',
      ],
      'Kiswahili': [
        'Kusikiliza na Kuzungumza',
        'Kusoma',
        'Kuandika',
        'Sarufi na Matumizi ya Lugha',
        'Fasihi',
      ],
      'Community Service Learning': [
        'Self and Community',
        'Community Needs Assessment',
        'Service Planning and Implementation',
        'Reflection and Evaluation',
      ],
      'Literature in English': [
        'Oral Literature',
        'Prose',
        'Drama',
        'Poetry',
        'Literary Appreciation',
      ],
      'Fasihi ya Kiswahili': [
        'Fasihi Simulizi',
        'Ushairi',
        'Hadithi Fupi na Riwaya',
        'Tamthilia',
        'Uhakiki wa Fasihi',
      ],
      'Arabic': [
        'Listening and Speaking',
        'Reading and Comprehension',
        'Writing and Composition',
        'Grammar and Language Use',
        'Islamic Culture and Literature',
      ],
      'French': [
        'Communication Orale',
        'Lecture et Compréhension',
        'Expression Écrite',
        'Grammaire',
        'Culture Francophone',
      ],
      'German': [
        'Hören und Sprechen',
        'Lesen und Verstehen',
        'Schreiben',
        'Grammatik',
        'Kultur und Landeskunde',
      ],
      'Chinese': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Grammar and Language Use',
        'Chinese Culture',
      ],
      'Indigenous Languages': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Grammar and Language Use',
        'Oral Literature and Culture',
      ],
      'Sign Language': [
        'Receptive Skills',
        'Expressive Skills',
        'Deaf Culture and History',
        'Sign Language Grammar',
      ],
      'Kenyan Sign Language': [
        'Receptive Skills',
        'Expressive Skills',
        'KSL Grammar and Structure',
        'Deaf Culture and History',
      ],
      'History and Citizenship': [
        'Pre-Colonial African History',
        'Colonial History of Kenya',
        'Governance and Citizenship',
        'Economic History',
      ],
      'Geography': [
        'Practical Geography',
        'Natural Systems and Processes',
        'Human and Economic Activities',
      ],
      'CRE': [
        'The Old Testament',
        'The New Testament',
        'Church in Action',
        'Christian Living Today',
      ],
      'IRE': [
        'Quran and Hadith',
        'Pillars of Islam',
        'Islamic History and Civilization',
        'Islamic Ethics and Values',
      ],
      'HRE': [
        'Hindu Scriptures and Philosophy',
        'Hindu Practices and Worship',
        'Hindu Ethics and Values',
        'Hindu Culture and Civilization',
      ],
      'Business Studies': [
        'Business Concepts and Environment',
        'Entrepreneurship',
        'Financial Literacy',
        'Marketing',
        'Office Management',
      ],
      'Biology': [
        'Cell Biology',
        'Biochemistry',
        'Classification of Living Things',
        'Nutrition',
        'Gaseous Exchange',
        'Transport and Excretion',
        'Ecology',
      ],
      'Chemistry': [
        'Atomic Structure and Periodic Table',
        'Chemical Bonding',
        'Acids, Bases and Salts',
        'Stoichiometry',
        'Electrochemistry',
        'Organic Chemistry',
        'Environmental Chemistry',
      ],
      'Physics': [
        'Mechanics',
        'Waves',
        'Electricity and Magnetism',
        'Thermal Physics',
        'Optics',
      ],
      'General Science': [
        'Matter and Its Properties',
        'Living Things and Their Environment',
        'Energy and Its Transformations',
        'Earth and Space',
        'Science and Technology in Society',
      ],
      'Agriculture': [
        'Crop Production',
        'Animal Production',
        'Soil and Water Management',
        'Farm Structures and Mechanisation',
        'Agricultural Economics',
      ],
      'Computer Studies': [
        'Computer Systems',
        'Programming Fundamentals',
        'Data and Information Management',
        'Networks and the Internet',
        'Digital Citizenship and Ethics',
      ],
      'Home Science': [
        'Food and Nutrition',
        'Clothing and Textiles',
        'Housing and Home Management',
        'Family Health',
      ],
      'Aviation': [
        'Introduction to Aviation',
        'Principles of Flight',
        'Aircraft Systems',
        'Air Navigation and Meteorology',
        'Aviation Safety and Regulations',
      ],
      'Building and Construction': [
        'Building Materials and Tools',
        'Site Preparation and Foundation',
        'Masonry and Carpentry',
        'Plumbing and Drainage',
        'Building Regulations and Safety',
      ],
      'Electricity': [
        'Electrical Theory and Principles',
        'Electrical Wiring and Installation',
        'Electrical Machines',
        'Electronics',
        'Electrical Safety',
      ],
      'Drawing and Design': [
        'Principles of Design',
        'Technical Drawing',
        'Freehand Drawing',
        'Graphic Design',
        'Design Projects',
      ],
      'Marine and Fisheries': [
        'Marine Ecosystems',
        'Fish Biology and Identification',
        'Fishing Methods and Technology',
        'Aquaculture',
        'Marine Resource Management',
      ],
      'Metalwork': [
        'Properties of Metals',
        'Hand Tools and Machine Tools',
        'Marking and Measuring',
        'Joining and Fabrication',
        'Heat Treatment and Finishing',
      ],
      'Power Mechanics': [
        'Internal Combustion Engines',
        'Engine Systems',
        'Power Transmission',
        'Maintenance and Repair',
        'Safety in Power Mechanics',
      ],
      'Woodwork': [
        'Properties of Wood',
        'Hand Tools and Power Tools',
        'Joints and Constructions',
        'Finishing and Surface Treatment',
        'Woodwork Projects',
      ],
      'Media Technology': [
        'Introduction to Media',
        'Photography and Videography',
        'Digital Media Production',
        'Media and Society',
        'Media Ethics',
      ],
      'Art and Design': [
        'Drawing and Painting',
        'Sculpture and Modelling',
        'Printmaking',
        'Textile Art',
        'Design and Aesthetics',
      ],
      'Music and Dance': [
        'Music Theory and Notation',
        'Vocal Music',
        'Instrumental Music',
        'Traditional and Contemporary Dance',
        'Music and Dance in Culture',
      ],
      'Theatre and Film': [
        'Introduction to Theatre',
        'Acting and Performance',
        'Directing and Production',
        'Film Studies',
        'Script Writing',
      ],
      'Fine Arts': [
        'Drawing and Composition',
        'Painting Techniques',
        'Sculpture and Three-Dimensional Art',
        'Art History and Appreciation',
        'Creative Projects',
      ],
      'Sports and Recreation': [
        'Principles of Sports Science',
        'Athletics and Track Events',
        'Team Sports',
        'Individual Sports',
        'Recreation and Leisure Activities',
      ],
      'Physical Education': [
        'Physical Fitness and Health',
        'Athletics',
        'Games and Sports',
        'Swimming and Water Safety',
        'Outdoor and Adventure Activities',
      ],
      'Life Skills Education': [
        'Self-Awareness and Identity',
        'Interpersonal Relationships',
        'Decision Making and Problem Solving',
        'Citizenship and Social Responsibility',
      ],
    },
  },

  'Grade 11': {
    subjects: [
      'Mathematics',
      'Essential Mathematics',
      'English',
      'Kiswahili',
      'Community Service Learning',
      'Literature in English',
      'Fasihi ya Kiswahili',
      'Arabic',
      'French',
      'German',
      'Chinese',
      'Indigenous Languages',
      'Sign Language',
      'Kenyan Sign Language',
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      'Biology',
      'Chemistry',
      'Physics',
      'General Science',
      'Agriculture',
      'Computer Studies',
      'Home Science',
      'Aviation',
      'Building and Construction',
      'Electricity',
      'Drawing and Design',
      'Marine and Fisheries',
      'Metalwork',
      'Power Mechanics',
      'Woodwork',
      'Media Technology',
      'Art and Design',
      'Music and Dance',
      'Theatre and Film',
      'Fine Arts',
      'Sports and Recreation',
      'Physical Education',
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Numbers and Algebra',
        'Sequences and Series',
        'Measurement and Geometry',
        'Statistics and Probability',
        'Financial Mathematics',
        'Calculus (Introductory)',
      ],
      'Essential Mathematics': [
        'Number and Operations',
        'Algebra and Graphs',
        'Measurement and Geometry',
        'Statistics and Data Analysis',
        'Financial Mathematics',
      ],
      'English': [
        'Listening and Speaking',
        'Reading',
        'Writing',
        'Language Use',
        'Literature',
      ],
      'Kiswahili': [
        'Kusikiliza na Kuzungumza',
        'Kusoma',
        'Kuandika',
        'Sarufi na Matumizi ya Lugha',
        'Fasihi',
      ],
      'Community Service Learning': [
        'Community Engagement and Partnerships',
        'Social Issues and Advocacy',
        'Project Management',
        'Civic Responsibility',
      ],
      'Literature in English': [
        'Oral Literature and Traditions',
        'Prose Fiction',
        'Drama and Performance',
        'Poetry and Versification',
        'Critical and Creative Writing',
      ],
      'Fasihi ya Kiswahili': [
        'Fasihi Simulizi ya Kina',
        'Ushairi wa Hali ya Juu',
        'Riwaya na Hadithi Fupi',
        'Tamthilia',
        'Uhakiki wa Fasihi',
      ],
      'Arabic': [
        'Advanced Listening and Speaking',
        'Reading and Text Analysis',
        'Composition and Creative Writing',
        'Advanced Grammar',
        'Arabic Literature',
      ],
      'French': [
        'Communication Avancée',
        'Analyse de Textes',
        'Composition et Rédaction',
        'Grammaire Avancée',
        'Littérature Française',
      ],
      'German': [
        'Fortgeschrittenes Hören und Sprechen',
        'Textanalyse',
        'Aufsatz und Kreatives Schreiben',
        'Fortgeschrittene Grammatik',
        'Deutsche Literatur',
      ],
      'Chinese': [
        'Advanced Listening and Speaking',
        'Reading and Text Analysis',
        'Advanced Writing',
        'Advanced Grammar',
        'Chinese Literature and Culture',
      ],
      'Indigenous Languages': [
        'Advanced Listening and Speaking',
        'Reading and Text Analysis',
        'Writing and Composition',
        'Advanced Grammar',
        'Oral Literature and Folklore',
      ],
      'Sign Language': [
        'Advanced Receptive Skills',
        'Advanced Expressive Skills',
        'Sign Language Linguistics',
        'Interpreting Skills',
      ],
      'Kenyan Sign Language': [
        'Advanced Receptive Skills',
        'Advanced Expressive Skills',
        'KSL Linguistics and Structure',
        'Interpreting and Transliteration',
      ],
      'History and Citizenship': [
        'Nationalism and Independence',
        'Post-Independence Kenya',
        'International Relations',
        'Constitutional Development',
        'Contemporary Issues',
      ],
      'Geography': [
        'Geomorphology',
        'Climatology',
        'Population Geography',
        'Urban Geography',
        'Agriculture and Land Use',
        'Industry and Trade',
      ],
      'CRE': [
        'Christian Living and Modern Challenges',
        'Human Sexuality and Relationships',
        'Social Justice and Stewardship',
        'Faith in Action',
      ],
      'IRE': [
        'Advanced Quran Studies',
        'Islamic Jurisprudence',
        'Islamic History and Scholars',
        'Contemporary Islamic Issues',
      ],
      'HRE': [
        'Advanced Hindu Philosophy',
        'Hindu Rituals and Festivals',
        'Hindu Social Ethics',
        'Contemporary Hindu Issues',
      ],
      'Business Studies': [
        'Business Operations',
        'Financial Accounting',
        'Human Resource Management',
        'Business Law',
        'Trade and Commerce',
      ],
      'Biology': [
        'Cell Biology and Biochemistry',
        'Genetics and Heredity',
        'Reproduction',
        'Growth and Development',
        'Regulation and Coordination',
        'Evolution',
        'Applied Biology',
      ],
      'Chemistry': [
        'Reaction Kinetics',
        'Chemical Equilibrium',
        'Thermochemistry',
        'Organic Chemistry',
        'Industrial Chemistry',
        'Analytical Chemistry',
      ],
      'Physics': [
        'Linear and Circular Motion',
        'Work, Energy and Power',
        'Electromagnetism',
        'Electronics',
        'Radioactivity',
        'Waves and Optics',
      ],
      'General Science': [
        'Advanced Matter and Properties',
        'Life Processes and Systems',
        'Forces and Energy',
        'Earth Systems and Space',
        'Applied Science and Technology',
      ],
      'Agriculture': [
        'Advanced Crop Production',
        'Livestock Management',
        'Soil Science',
        'Agricultural Engineering',
        'Farm Business Management',
      ],
      'Computer Studies': [
        'Advanced Programming',
        'Database Management',
        'Web Technologies',
        'Algorithms and Data Structures',
        'Cybersecurity',
      ],
      'Home Science': [
        'Advanced Food Science',
        'Textile Technology',
        'Household Management',
        'Entrepreneurship in Home Science',
      ],
      'Aviation': [
        'Advanced Principles of Flight',
        'Navigation Systems',
        'Aircraft Maintenance',
        'Air Traffic Management',
        'Aviation Law and Regulations',
      ],
      'Building and Construction': [
        'Advanced Masonry',
        'Roofing and Flooring',
        'Structural Design',
        'Electrical and Plumbing Integration',
        'Project Management in Construction',
      ],
      'Electricity': [
        'Advanced Circuit Analysis',
        'Industrial Wiring',
        'Electrical Machines and Motors',
        'Renewable Energy Systems',
        'Electrical Project Work',
      ],
      'Drawing and Design': [
        'Advanced Technical Drawing',
        'Computer-Aided Design (CAD)',
        'Product Design',
        'Architectural Drawing',
        'Design Portfolio',
      ],
      'Marine and Fisheries': [
        'Marine Biology',
        'Advanced Fishing Technology',
        'Aquaculture Management',
        'Marine Environmental Management',
        'Fish Processing and Value Addition',
      ],
      'Metalwork': [
        'Advanced Fabrication',
        'Welding and Joining Techniques',
        'Machine Operations',
        'Sheet Metal Work',
        'Metalwork Projects',
      ],
      'Power Mechanics': [
        'Advanced Engine Systems',
        'Fuel and Lubrication Systems',
        'Electrical Systems in Vehicles',
        'Diagnostics and Troubleshooting',
        'Power Mechanics Projects',
      ],
      'Woodwork': [
        'Advanced Joinery',
        'Cabinet Making',
        'Wood Turning and Carving',
        'Furniture Design and Construction',
        'Woodwork Projects',
      ],
      'Media Technology': [
        'Advanced Photography',
        'Video Production and Editing',
        'Radio and Podcast Production',
        'Social Media and Digital Marketing',
        'Media Law and Ethics',
      ],
      'Art and Design': [
        'Advanced Drawing and Painting',
        'Ceramics and Sculpture',
        'Graphic Design and Typography',
        'Fashion Design',
        'Art Portfolio Development',
      ],
      'Music and Dance': [
        'Harmony and Counterpoint',
        'Choral Music',
        'Instrumental Ensemble',
        'Choreography and Dance Composition',
        'Music and Dance Production',
      ],
      'Theatre and Film': [
        'Advanced Acting Techniques',
        'Theatre Production',
        'Film Production and Editing',
        'Drama and Society',
        'Performance and Critique',
      ],
      'Fine Arts': [
        'Advanced Drawing Techniques',
        'Mixed Media and Experimental Art',
        'Digital Art',
        'Contemporary African Art',
        'Art Exhibition and Critique',
      ],
      'Sports and Recreation': [
        'Exercise Physiology',
        'Sports Psychology',
        'Coaching and Training Techniques',
        'Sports Management',
        'Sports Nutrition and Injury Prevention',
      ],
      'Physical Education': [
        'Advanced Physical Fitness',
        'Athletics and Track and Field',
        'Games Strategy and Tactics',
        'Sports Leadership and Officiating',
        'Health and Wellness',
      ],
      'Life Skills Education': [
        'Conflict Resolution',
        'Financial Literacy and Planning',
        'Career Guidance',
        'Mental Health and Wellbeing',
      ],
    },
  },

  'Grade 12': {
    subjects: [
      'Mathematics',
      'Essential Mathematics',
      'English',
      'Kiswahili',
      'Community Service Learning',
      'Literature in English',
      'Fasihi ya Kiswahili',
      'Arabic',
      'French',
      'German',
      'Chinese',
      'Indigenous Languages',
      'Sign Language',
      'Kenyan Sign Language',
      'History and Citizenship',
      'Geography',
      'CRE',
      'IRE',
      'HRE',
      'Business Studies',
      'Biology',
      'Chemistry',
      'Physics',
      'General Science',
      'Agriculture',
      'Computer Studies',
      'Home Science',
      'Aviation',
      'Building and Construction',
      'Electricity',
      'Drawing and Design',
      'Marine and Fisheries',
      'Metalwork',
      'Power Mechanics',
      'Woodwork',
      'Media Technology',
      'Art and Design',
      'Music and Dance',
      'Theatre and Film',
      'Fine Arts',
      'Sports and Recreation',
      'Physical Education',
      'Life Skills Education',
    ],
    strands: {
      'Mathematics': [
        'Advanced Algebra',
        'Calculus',
        'Vectors and Matrices',
        'Statistics and Probability',
        'Financial Mathematics',
        'Complex Numbers',
      ],
      'Essential Mathematics': [
        'Advanced Number and Operations',
        'Applied Algebra',
        'Advanced Measurement',
        'Statistical Analysis',
        'Personal Financial Management',
      ],
      'English': [
        'Advanced Listening and Speaking',
        'Critical Reading',
        'Advanced Writing',
        'Language and Style',
        'Literature and Criticism',
      ],
      'Kiswahili': [
        'Mawasiliano ya Hali ya Juu',
        'Usomaji wa Kina',
        'Uandishi wa Hali ya Juu',
        'Sarufi ya Kina',
        'Fasihi ya Kina',
      ],
      'Community Service Learning': [
        'Social Enterprise and Innovation',
        'Community Impact Assessment',
        'Leadership and Change',
        'Global Citizenship',
      ],
      'Literature in English': [
        'Advanced Oral Literature',
        'The Novel and Short Story',
        'Advanced Drama',
        'Advanced Poetry',
        'Comparative Literature',
      ],
      'Fasihi ya Kiswahili': [
        'Fasihi Simulizi ya Kina Zaidi',
        'Ushairi wa Hali ya Juu Zaidi',
        'Riwaya ya Kina',
        'Tamthilia ya Kina',
        'Uhakiki Linganishi wa Fasihi',
      ],
      'Arabic': [
        'Advanced Arabic Communication',
        'Classical Arabic Literature',
        'Modern Arabic Literature',
        'Advanced Arabic Grammar',
        'Arabic Research and Composition',
      ],
      'French': [
        'Communication de Haut Niveau',
        'Littérature Française Avancée',
        'Rédaction et Recherche',
        'Grammaire de Haut Niveau',
        'Francophonie et Mondialisation',
      ],
      'German': [
        'Fortgeschrittene Kommunikation',
        'Deutsche Literatur Vertieft',
        'Schreiben und Forschung',
        'Grammatik auf hohem Niveau',
        'Deutschland und die Welt',
      ],
      'Chinese': [
        'Advanced Chinese Communication',
        'Classical Chinese Literature',
        'Modern Chinese Literature',
        'Advanced Chinese Grammar',
        'China and the World',
      ],
      'Indigenous Languages': [
        'Advanced Language Use',
        'Oral Literature and Preservation',
        'Language and Identity',
        'Creative Writing',
        'Language Research',
      ],
      'Sign Language': [
        'Professional Sign Language',
        'Sign Language Research',
        'Interpreting and Translation',
        'Deaf Community Advocacy',
      ],
      'Kenyan Sign Language': [
        'Professional KSL Communication',
        'KSL Research and Documentation',
        'Professional Interpreting',
        'Deaf Community Development',
      ],
      'History and Citizenship': [
        'Kenya and the Global Community',
        'Democracy and Governance',
        'Economic Development and Planning',
        'Human Rights and Justice',
        'Contemporary African Issues',
      ],
      'Geography': [
        'Environmental Management',
        'Global Issues and Sustainable Development',
        'Advanced Map Work and GIS',
        'Transport and Trade',
        'Regional Studies',
      ],
      'CRE': [
        'Christian Responses to Contemporary Issues',
        'Peace and Justice',
        'Christian Vocation and Service',
        'Interfaith Dialogue',
      ],
      'IRE': [
        'Advanced Islamic Jurisprudence',
        'Islamic Economics and Finance',
        'Islam and Contemporary Issues',
        'Islamic Research and Scholarship',
      ],
      'HRE': [
        'Advanced Hindu Philosophy',
        'Hindu Responses to Contemporary Issues',
        'Hinduism and World Religions',
        'Hindu Research and Scholarship',
      ],
      'Business Studies': [
        'Advanced Financial Management',
        'Strategic Management',
        'Global Business',
        'Business Innovation and Entrepreneurship',
      ],
      'Biology': [
        'Molecular Biology and Biotechnology',
        'Ecology and Conservation',
        'Applied Genetics',
        'Human Physiology',
        'Evolution and Biodiversity',
        'Environmental Biology',
      ],
      'Chemistry': [
        'Advanced Organic Chemistry',
        'Environmental and Green Chemistry',
        'Advanced Electrochemistry',
        'Chemical Analysis',
        'Industrial Processes',
        'Nanochemistry (Introduction)',
      ],
      'Physics': [
        'Advanced Mechanics',
        'Electromagnetism and Electronics',
        'Nuclear Physics',
        'Astrophysics (Introduction)',
        'Quantum Physics (Introduction)',
        'Applied Physics',
      ],
      'General Science': [
        'Science Research Methods',
        'Environmental Science',
        'Applied Physics and Chemistry',
        'Life Sciences and Biotechnology',
        'Science, Technology and Society',
      ],
      'Agriculture': [
        'Farm Enterprise Management',
        'Sustainable Agriculture',
        'Value Addition and Agribusiness',
        'Research and Innovation in Agriculture',
      ],
      'Computer Studies': [
        'Advanced Programming',
        'Artificial Intelligence (Introductory)',
        'Cloud Computing',
        'Software Engineering',
        'Data Science Fundamentals',
      ],
      'Home Science': [
        'Advanced Nutrition and Dietetics',
        'Fashion Design and Technology',
        'Home-Based Enterprise',
        'Community Development',
      ],
      'Aviation': [
        'Commercial Aviation Operations',
        'Advanced Navigation',
        'Aviation Business Management',
        'Safety Management Systems',
        'Aviation Research Project',
      ],
      'Building and Construction': [
        'Advanced Structural Work',
        'Interior Finishing',
        'Construction Project Management',
        'Sustainable Building Practices',
        'Construction Research Project',
      ],
      'Electricity': [
        'Advanced Industrial Electricity',
        'Solar and Renewable Energy',
        'Smart Electrical Systems',
        'Electrical Entrepreneurship',
        'Electrical Research Project',
      ],
      'Drawing and Design': [
        'Advanced CAD and Digital Design',
        'Industrial Design',
        'Environmental and Spatial Design',
        'Design Entrepreneurship',
        'Design Research Project',
      ],
      'Marine and Fisheries': [
        'Advanced Aquaculture',
        'Marine Conservation',
        'Fish Business and Entrepreneurship',
        'Marine Research Methods',
        'Marine and Fisheries Project',
      ],
      'Metalwork': [
        'Advanced Welding',
        'Precision Engineering',
        'Metal Fabrication Projects',
        'Metalwork Entrepreneurship',
        'Research and Innovation in Metalwork',
      ],
      'Power Mechanics': [
        'Advanced Automotive Systems',
        'Heavy Equipment Mechanics',
        'Power Mechanics Entrepreneurship',
        'Environmental Considerations',
        'Power Mechanics Research Project',
      ],
      'Woodwork': [
        'Advanced Furniture Making',
        'Wood Technology',
        'Woodwork Entrepreneurship',
        'Sustainable Wood Use',
        'Woodwork Research Project',
      ],
      'Media Technology': [
        'Advanced Film and TV Production',
        'Digital Marketing and Branding',
        'Media Entrepreneurship',
        'Media Research and Analysis',
        'Media Technology Project',
      ],
      'Art and Design': [
        'Professional Studio Practice',
        'Art and Design Entrepreneurship',
        'Community Art and Design',
        'Art Research and Criticism',
        'Final Art Portfolio',
      ],
      'Music and Dance': [
        'Music Composition and Arrangement',
        'Professional Performance',
        'Music and Dance Entrepreneurship',
        'Music Technology',
        'Music and Dance Research Project',
      ],
      'Theatre and Film': [
        'Professional Theatre Production',
        'Advanced Film Making',
        'Theatre and Film Entrepreneurship',
        'Theatre Research and Criticism',
        'Final Theatre or Film Project',
      ],
      'Fine Arts': [
        'Professional Art Practice',
        'Art Entrepreneurship',
        'Community and Public Art',
        'Advanced Art Research',
        'Final Art Exhibition',
      ],
      'Sports and Recreation': [
        'Advanced Sports Science',
        'Sports Business and Entrepreneurship',
        'Sports Research Methods',
        'Community Sports Development',
        'Sports Career Pathways',
      ],
      'Physical Education': [
        'Advanced Sports Performance',
        'Sports Science and Research',
        'PE Leadership and Teaching',
        'Sports Entrepreneurship',
        'Health Promotion and Community Fitness',
      ],
      'Life Skills Education': [
        'Entrepreneurship and Innovation',
        'Civic Education and Governance',
        'Global Citizenship',
        'Transition to Adulthood',
      ],
    },
  },
}

// Sub-strands mapped to strands
export const SUBSTRANDS = {
  // Mathematics
  'Numbers and Algebra': ['Indices and Logarithms', 'Quadratic Equations', 'Inequalities', 'Simultaneous Equations', 'Polynomials'],
  'Sequences and Series': ['Arithmetic Progressions', 'Geometric Progressions', 'Binomial Theorem', 'Sum to Infinity'],
  'Measurement and Geometry': ['Trigonometry', 'Circles and Chords', 'Vectors in 2D and 3D', 'Transformation Geometry', 'Constructions'],
  'Statistics and Probability': ['Measures of Central Tendency', 'Measures of Dispersion', 'Probability Theory', 'Distributions', 'Data Representation'],
  'Financial Mathematics': ['Commercial Arithmetic', 'Simple and Compound Interest', 'Annuities and Investments', 'Depreciation'],
  'Calculus (Introductory)': ['Limits and Continuity', 'Differentiation', 'Integration', 'Applications of Calculus'],
  'Calculus': ['Advanced Differentiation', 'Advanced Integration', 'Differential Equations', 'Applications'],
  'Advanced Algebra': ['Complex Numbers', 'Matrices and Determinants', 'Partial Fractions', 'Mathematical Induction'],
  'Vectors and Matrices': ['Matrix Operations', 'Determinants and Inverses', 'Transformations', 'Linear Equations'],

  // Essential Mathematics
  'Number and Operations': ['Whole Numbers and Integers', 'Fractions and Decimals', 'Percentages', 'Ratios and Proportions'],
  'Data Handling': ['Data Collection', 'Tables and Charts', 'Measures of Central Tendency', 'Interpretation of Data'],

  // English
  'Listening and Speaking': ['Oral Presentation', 'Listening Comprehension', 'Discussion and Debate', 'Public Speaking'],
  'Reading': ['Comprehension Skills', 'Skimming and Scanning', 'Inference and Deduction', 'Critical Reading'],
  'Writing': ['Composition Writing', 'Summary Writing', 'Letter and Report Writing', 'Creative Writing'],
  'Language Use': ['Grammar and Syntax', 'Vocabulary Development', 'Punctuation', 'Style and Register'],
  'Literature': ['Prose Analysis', 'Drama Analysis', 'Poetry Analysis', 'Literary Devices'],

  // Kiswahili
  'Kusikiliza na Kuzungumza': ['Uwasiliano wa Mdomo', 'Mazungumzo na Mijadala', 'Hotuba na Uwasilishaji', 'Kusikiliza kwa Makini'],
  'Kusoma': ['Ufahamu wa Kusoma', 'Kusoma kwa Haraka', 'Uchambuzi wa Maandishi', 'Kusoma kwa Kina'],
  'Kuandika': ['Insha', 'Muhtasari', 'Barua na Ripoti', 'Uandishi wa Ubunifu'],
  'Sarufi na Matumizi ya Lugha': ['Sarufi ya Kiswahili', 'Msamiati', 'Alama za Uakifishaji', 'Rejista na Mtindo'],
  'Fasihi': ['Ushairi', 'Hadithi Fupi', 'Riwaya', 'Tamthilia', 'Vipengele vya Fasihi'],

  // Biology
  'Cell Biology': ['Cell Structure and Function', 'Cell Division (Mitosis and Meiosis)', 'Cell Transport', 'Biochemical Reactions'],
  'Cell Biology and Biochemistry': ['Biomolecules', 'Enzyme Action', 'ATP and Energy', 'Metabolic Pathways'],
  'Genetics and Heredity': ['Mendelian Genetics', 'Dihybrid Cross', 'Linkage and Sex-Linked Traits', 'Genetic Disorders'],
  'Reproduction': ['Sexual Reproduction in Humans', 'Reproduction in Plants', 'Fertilisation and Development', 'Reproductive Health'],
  'Regulation and Coordination': ['Nervous System', 'Endocrine System', 'Homeostasis', 'Receptors and Effectors'],
  'Ecology': ['Ecosystems and Biomes', 'Food Webs and Energy Flow', 'Population Ecology', 'Conservation Biology'],
  'Molecular Biology and Biotechnology': ['DNA Structure and Replication', 'Protein Synthesis', 'Genetic Engineering', 'Biotechnology Applications'],
  'Nutrition': ['Types of Nutrients', 'Digestion and Absorption', 'Malnutrition and Deficiency Diseases', 'Balanced Diet'],
  'Gaseous Exchange': ['Structure of Respiratory System', 'Mechanism of Breathing', 'Gas Exchange in Plants', 'Respiratory Diseases'],
  'Transport and Excretion': ['Blood and Blood Groups', 'Heart and Circulation', 'Excretory Organs', 'Kidney Function'],

  // Chemistry
  'Atomic Structure and Periodic Table': ['Atomic Models', 'Electronic Configuration', 'Periodic Trends', 'Chemical Families'],
  'Acids, Bases and Salts': ['pH and Indicators', 'Titration and Neutralisation', 'Salt Formation', 'Buffer Solutions'],
  'Stoichiometry': ['Mole Concept', 'Empirical Formulae', 'Limiting Reagent', 'Yield Calculations'],
  'Organic Chemistry': ['Hydrocarbons', 'Functional Groups', 'Reactions of Organic Compounds', 'Polymers'],
  'Reaction Kinetics': ['Rate of Reaction', 'Factors Affecting Rate', 'Activation Energy', 'Catalysis'],
  'Chemical Equilibrium': ["Le Chatelier's Principle", 'Equilibrium Constant', 'Industrial Applications', 'Ionic Equilibria'],
  'Thermochemistry': ['Enthalpy Changes', "Hess's Law", 'Bond Energies', 'Calorimetry'],
  'Electrochemistry': ['Electrolysis', 'Electrochemical Cells', 'Electrode Potentials', 'Industrial Applications'],
  'Environmental Chemistry': ['Water Treatment', 'Air Pollution', 'Soil Chemistry', 'Green Chemistry'],

  // Physics
  'Mechanics': ["Newton's Laws of Motion", 'Momentum and Impulse', 'Work, Energy and Power', 'Projectile Motion'],
  'Linear and Circular Motion': ['Equations of Motion', 'Circular Motion', 'Angular Velocity', 'Centripetal Force'],
  'Electromagnetism': ['Magnetic Fields', 'Electromagnetic Induction', 'AC and DC Circuits', 'Transformers'],
  'Waves': ['Wave Properties', 'Sound Waves', 'Electromagnetic Spectrum', 'Interference and Diffraction'],
  'Radioactivity': ['Nuclear Structure', 'Types of Radiation', 'Half-Life', 'Nuclear Reactions and Safety'],
  'Electronics': ['Semiconductors', 'Diodes and Transistors', 'Logic Gates', 'Amplifiers'],
  'Thermal Physics': ['Heat and Temperature', 'Thermodynamic Processes', 'Heat Transfer', 'Gas Laws'],
  'Optics': ['Reflection of Light', 'Refraction and Lenses', 'Optical Instruments', 'Dispersion of Light'],

  // History
  'Pre-Colonial African History': ['African Political Systems', 'Trade and Economy', 'Social Organisation', 'African Religions'],
  'Colonial History of Kenya': ['European Exploration', 'Establishment of Colonial Rule', 'African Resistance', 'Colonial Economic Policies'],
  'Nationalism and Independence': ['African Nationalism', 'Kenya African Union', 'Mau Mau', 'Independence Negotiations'],
  'Post-Independence Kenya': ['Constitutional Developments', 'Political Parties', 'Economic Policies', 'Social Development'],
  'Governance and Citizenship': ['Structures of Government', 'Rights and Responsibilities', 'Rule of Law', 'Democratic Governance'],
  'International Relations': ['Kenya and East Africa', 'Kenya and the African Union', 'Kenya and the United Nations', 'Foreign Policy'],
  'Contemporary Issues': ['Ethnic Relations', 'Environmental Challenges', 'Technology and Society', 'Globalisation'],

  // Geography — Official KICD Grade 10 Strands & Sub-strands
  'Practical Geography': [
    'Introduction to Geography',
    'Map Reading and Interpretation',
    'Statistical Methods',
    'Geographic Information System',
  ],
  'Natural Systems and Processes': [
    'Rocks',
    'Earth Movements',
    'Folding',
    'Vulcanicity',
    'Earthquakes',
  ],
  'Human and Economic Activities': [
    'Agriculture',
    'Mining',
    'Energy',
    'Industry',
  ],

  // Business Studies
  'Business Concepts and Environment': ['Nature of Business', 'Business Environment', 'Forms of Business Ownership', 'Business Objectives'],
  'Entrepreneurship': ['Entrepreneurial Traits', 'Business Opportunities', 'Business Plan', 'Start-Up Challenges'],
  'Financial Accounting': ['Double Entry Bookkeeping', 'Final Accounts', 'Bank Reconciliation', 'Interpretation of Accounts'],
  'Financial Literacy': ['Personal Finance', 'Budgeting', 'Investment Options', 'Taxation'],
  'Marketing': ['Market Research', 'Marketing Mix', 'Consumer Behaviour', 'Digital Marketing'],
  'Office Management': ['Office Organisation', 'Communication in Business', 'Record Keeping', 'Office Technology'],
  'Business Operations': ['Production Management', 'Supply Chain', 'Quality Management', 'Inventory Control'],

  // Agriculture
  'Crop Production': ['Crop Ecology', 'Land Preparation', 'Planting and Spacing', 'Crop Management and Harvesting'],
  'Animal Production': ['Livestock Selection', 'Animal Nutrition', 'Animal Health', 'Livestock Records'],
  'Soil and Water Management': ['Soil Formation and Types', 'Soil Fertility', 'Irrigation Methods', 'Drainage and Conservation'],
  'Agricultural Economics': ['Farm Planning', 'Costs and Returns', 'Agricultural Marketing', 'Credit and Finance'],
  'Farm Structures and Mechanisation': ['Farm Layouts', 'Farm Buildings', 'Agricultural Tools', 'Machinery Maintenance'],

  // Computer Studies
  'Computer Systems': ['Hardware Components', 'Software Types', 'Operating Systems', 'Computer Maintenance'],
  'Programming Fundamentals': ['Problem Solving', 'Algorithms and Flowcharts', 'Coding Basics', 'Debugging'],
  'Data and Information Management': ['Data Types', 'Spreadsheets', 'Databases', 'Data Security'],
  'Networks and the Internet': ['Network Types', 'Internet Services', 'Email and Communication', 'Cloud Computing'],
  'Digital Citizenship and Ethics': ['Online Safety', 'Intellectual Property', 'Digital Footprint', 'Responsible Technology Use'],

  // Home Science
  'Food and Nutrition': ['Nutrients and Functions', 'Meal Planning', 'Food Preparation', 'Food Safety and Hygiene'],
  'Clothing and Textiles': ['Fibres and Fabrics', 'Sewing Techniques', 'Garment Construction', 'Laundry and Care'],
  'Housing and Home Management': ['Home Organisation', 'Interior Design', 'Home Safety', 'Home Maintenance'],
  'Family Health': ['Personal Hygiene', 'Common Illnesses', 'First Aid', 'Family Planning'],

  // CRE
  'The Old Testament': ['The Holy Bible', 'The Exodus', 'The Sinai Covenant', 'Loyalty to God (Elijah)', 'Old Testament Prophets and Prophet Amos'],
  'The New Testament': ['New Testament Books', 'Infancy and Early Life of Jesus Christ', 'Galilean Ministry', "Paul's First Letter to the Corinthians"],
  'Church in Action': ['The Holy Spirit and Gifts of the Holy Spirit', 'The Holy Trinity', 'Sacraments'],
  'Christian Living Today': ['Christian Ethics', 'Human Rights and Gender-Based Violence', 'Human Sexuality', 'Marriage and Family', 'Christian Response to Medicine and Technology'],

  // IRE
  'Quran and Hadith': ['Quranic Recitation and Memorisation', 'Interpretation of Quran', 'Hadith Collection', 'Application of Hadith'],
  'Pillars of Islam': ['Shahada', 'Salah', 'Zakat', 'Sawm', 'Hajj'],
  'Islamic History and Civilization': ['Early Islamic History', 'Islamic Golden Age', 'Islamic Scholars', 'Islam in East Africa'],
  'Islamic Ethics and Values': ['Moral Values', 'Family Life in Islam', 'Social Justice', 'Islamic Economics'],

  // Aviation
  'Introduction to Aviation': ['History of Aviation', 'Types of Aircraft', 'Aviation Industry', 'Career Opportunities in Aviation'],
  'Principles of Flight': ['Lift and Thrust', 'Drag and Weight', 'Aircraft Performance', 'Flight Controls'],
  'Aircraft Systems': ['Airframe', 'Propulsion Systems', 'Hydraulics', 'Avionics'],
  'Air Navigation and Meteorology': ['Navigation Instruments', 'Charts and Maps', 'Weather Patterns', 'Meteorological Hazards'],
  'Aviation Safety and Regulations': ['Safety Procedures', 'Emergency Protocols', 'KCAA Regulations', 'ICAO Standards'],

  // Building and Construction
  'Building Materials and Tools': ['Bricks and Mortar', 'Concrete and Steel', 'Timber and Roofing Materials', 'Hand Tools and Power Tools'],
  'Site Preparation and Foundation': ['Site Surveying', 'Excavation', 'Foundation Types', 'Drainage Systems'],
  'Masonry and Carpentry': ['Bricklaying', 'Blockwork', 'Timber Framing', 'Doors and Windows'],
  'Plumbing and Drainage': ['Pipe Systems', 'Water Supply', 'Waste Disposal', 'Sanitation Systems'],

  // Electricity
  'Electrical Theory and Principles': ['Current, Voltage and Resistance', "Ohm's Law", 'Series and Parallel Circuits', 'Electrical Power'],
  'Electrical Wiring and Installation': ['Domestic Wiring', 'Switchgear and Controls', 'Safety Devices', 'Wiring Diagrams'],
  'Electrical Machines': ['Electric Motors', 'Generators', 'Transformers', 'Motor Maintenance'],

  // Physical Education
  'Physical Fitness and Health': ['Components of Fitness', 'Exercise and Health', 'Body Composition', 'Fitness Testing'],
  'Athletics': ['Sprints and Relays', 'Middle and Long Distance', 'Jumps', 'Throws'],
  'Games and Sports': ['Football', 'Basketball', 'Volleyball', 'Netball', 'Hockey'],
  'Swimming and Water Safety': ['Swimming Strokes', 'Water Safety Rules', 'Lifesaving', 'Competitive Swimming'],

  // Music and Dance
  'Music Theory and Notation': ['Note Values', 'Scales and Keys', 'Time Signatures', 'Sight Reading'],
  'Vocal Music': ['Breathing and Voice Production', 'Choral Singing', 'Solo Performance', 'Traditional Kenyan Music'],
  'Instrumental Music': ['Keyboard Instruments', 'String Instruments', 'Wind Instruments', 'Percussion Instruments'],
  'Traditional and Contemporary Dance': ['Traditional Kenyan Dances', 'Contemporary Dance Styles', 'Dance Composition', 'Performance Skills'],

  // Theatre and Film
  'Introduction to Theatre': ['History of Theatre', 'Elements of Drama', 'Theatre Spaces', 'Theatre Practitioners'],
  'Acting and Performance': ['Character Development', 'Voice and Movement', 'Improvisation', 'Rehearsal Techniques'],
  'Directing and Production': ['The Director\'s Role', 'Set Design', 'Lighting and Sound', 'Costume and Makeup'],
  'Film Studies': ['History of Film', 'Film Genres', 'Film Language', 'Kenyan Cinema'],

  // Life Skills
  'Self-Awareness and Identity': ['Personal Values', 'Emotional Intelligence', 'Self-Esteem', 'Goal Setting'],
  'Interpersonal Relationships': ['Communication Skills', 'Peer Relationships', 'Family Relationships', 'Conflict Management'],
  'Decision Making and Problem Solving': ['Critical Thinking', 'Identifying Options', 'Evaluating Consequences', 'Creative Problem Solving'],
  'Citizenship and Social Responsibility': ['Community Participation', 'Environmental Responsibility', 'Volunteerism', 'Social Justice'],
}

export const TERMS = ['Term 1', 'Term 2', 'Term 3']
export const MARKS_OPTIONS = [30, 40, 50, 70, 80, 100]
export const QUESTIONS_OPTIONS = [10, 12, 15, 20, 25]
export const GRADES = Object.keys(CBC_CURRICULUM)

// ── GRADE STATUS ─────────────────────────────────────────
export const GRADE_STATUS = {
  'Grade 10': {
    active: true,
    label: 'Grade 10',
    note: 'Available Now',
    launchDate: null,
  },
  'Grade 11': {
    active: false,
    label: 'Grade 11',
    note: 'Coming Soon',
    launchDate: 'Term 2 2026',
  },
  'Grade 12': {
    active: false,
    label: 'Grade 12',
    note: 'Coming Soon',
    launchDate: 'Term 1 2027',
  },
}

// ── CAT MARKS OPTIONS ────────────────────────────────────
export const CAT_MARKS_OPTIONS = [20, 25, 30, 40]

// ── SUBJECT-SPECIFIC MARKS ───────────────────────────────
const SUBJECT_EXAM_MARKS = {
  'Mathematics': { 'End Term': 100, 'End Year': 100, 'Mock': 100, 'Pre-Mock': 100, 'Series': 100 },
  'Essential Mathematics': { 'End Term': 100, 'End Year': 100, 'Mock': 100, 'Pre-Mock': 100, 'Series': 100 },
  'English': { 'End Term': 100, 'End Year': 100, 'Mock': 100, 'Pre-Mock': 100, 'Series': 100 },
  'Kiswahili': { 'End Term': 100, 'End Year': 100, 'Mock': 100, 'Pre-Mock': 100, 'Series': 100 },
  'Biology': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Chemistry': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Physics': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Geography': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'History and Citizenship': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'CRE': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'IRE': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'HRE': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Business Studies': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Agriculture': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Computer Studies': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
  'Home Science': { 'End Term': 80, 'End Year': 80, 'Mock': 80, 'Pre-Mock': 80, 'Series': 80 },
}

// ── getExamTypeMarks ─────────────────────────────────────
export function getExamTypeMarks(subject, examType) {
  return SUBJECT_EXAM_MARKS[subject]?.[examType] ?? null
}

// ── UPDATED EXAM TYPES (matches ExamForm) ────────────────
export const EXAM_TYPES = ['CAT', 'Midterm', 'End Term', 'End Year', 'Pre-Mock', 'Mock', 'Series']
